name: Semgrep Full Scan with Issues

on:
  workflow_dispatch:
    branches:
      - develop
  schedule:
    - cron: '0 1 * * 6'

jobs:
  semgrep-full:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      # Step 1: Clone application source code
      - name: Clone application source code
        uses: actions/checkout@v3

      # Step 2: Full scan with Semgrep
      - name: Full scan with Semgrep
        run: |
          semgrep \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default"
      # step 3
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.sarif
          path: report.sarif
            
      # step 4
      - name: Download report
        uses: actions/download-artifact@v3
        with: 
          name: report.sarif
      
      # Step 3: Parse SARIF and create GitHub Issues
      - name: Parse SARIF and Create Issues
        run: |
          # Install jq to parse JSON
          sudo apt-get install -y jq

          # Parse SARIF and extract results
          results=$(jq -c '.runs[].tool.driver.rules[]' report.sarif)

          # Iterate through each result and create an issue
          echo "${results}" | while read -r result; do
            rule_id=$(echo "$result" | jq -r '.id')
            description=$(echo "$result" | jq -r '.fullDescription.text')
            help_url=$(echo "$result" | jq -r '.helpUri')
            severity=$(echo "$result" | jq -r '.properties.precision')

            # Create GitHub Issue
            gh api repos/${{ github.repository }}/issues \
              -f title="Semgrep Issue: ${rule_id}" \
              -f body="**Description:**\n${description}\n\n**Severity:** ${severity}\n\n[Learn more about this issue](${help_url})" \
              -f labels="semgrep,security"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
