name: cppcheck-action-test
on: 
  workflow_dispatch:
    branches: [ "develop" ]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      # 리포지토리 체크아웃
      - uses: actions/checkout@v2
          
      # Cppcheck 실행
      - name: Run Cppcheck
        run: |
          cppcheck --enable=all --project=compile_commands.json \
                   --output-file=cppcheck-results.sarif --template=sarif
        continue-on-error: true # 오류가 있어도 실행을 계속함
      
      # SARIF 파일 업로드 (GitHub Security 탭)
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cppcheck-results.sarif
